package api

import "github.com/gin-gonic/gin"

func GetHomeInfo(ctx *gin.Context)
func GetHomeGeneralInfo(ctx *gin.Context)
func UpdateHomeGeneralInfo(ctx *gin.Context)
func GetPlanParagrarph(ctx *gin.Context)
func UpdatePlanParagraph(ctx *gin.Context)
func GetHomePlans(ctx *gin.Context)
func GetPlanByID(ctx *gin.Context)
func CreatePlan(ctx *gin.Context)
func DeletePlanByID(ctx *gin.Context)
func ReplacePlanByID(ctx *gin.Context)
func GetAdsInfo(ctx *gin.Context)
func UpdateAdsInfo(ctx *gin.Context)
func GetHomeProducts(ctx *gin.Context)
func GetProductByID(ctx *gin.Context)
func CreateHomeProduct(ctx *gin.Context)
func DeleteHomeProduct(ctx *gin.Context)
func UpdateHomeProduct(ctx *gin.Context)
func DeleteHomeProductByID(ctx *gin.Context)
func GetProductCategories(ctx *gin.Context)
func GetCategoryProducts(ctx *gin.Context)
func GetProductsOfCategory(ctx *gin.Context)
func CreateProductCategory(ctx *gin.Context)
func DeleteProductCategoryByID(ctx *gin.Context)
func DeleteProductCategoryByName(ctx *gin.Context)
func MoveProductToCategory(ctx *gin.Context)
func DeleteProductsOfCategory(ctx *gin.Context)
func ProductExistsUnderCategory(ctx *gin.Context)
func GetContacts(ctx *gin.Context)
func UpdateContacts(ctx *gin.Context)
